<a href="https://colab.research.google.com/github/Jakiaa/Python-Basic/blob/main/Array_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic mathematical functions are available as operators and also as functions in NumPy. 
It operates element-wise on an array. 

In [1]:
#import numpy packages
import numpy as np

In [4]:
# get input of two array
x=np.array([[3,5,7],[11,9,1]])
y=np.array([[2,4,6],[8,10,12]])

#Elementwise sum; both produce the array sum
print(x+y)
#or
print (np.add(x,y))

[[ 5  9 13]
 [19 19 13]]
[[ 5  9 13]
 [19 19 13]]


In [6]:
# Elementwise difference; both produce the array
print(x-y)
     #or
print (np.subtract(x,y))

[[  1   1   1]
 [  3  -1 -11]]
[[  1   1   1]
 [  3  -1 -11]]


In [7]:
# Elementwise product; both produce the array
print(x*y)
     #or
print (np.multiply(x,y))

[[ 6 20 42]
 [88 90 12]]
[[ 6 20 42]
 [88 90 12]]


In [10]:
# Elementwise division; both produce the array
print(x/y)
     #or
print (np.divide(x,y))

[[1.5        1.25       1.16666667]
 [1.375      0.9        0.08333333]]
[[1.5        1.25       1.16666667]
 [1.375      0.9        0.08333333]]


In [11]:
# Elementwise square root; produces the array
print(np.sqrt(x))
 

[[1.73205081 2.23606798 2.64575131]
 [3.31662479 3.         1.        ]]


We can use the “dot” function to calculate inner products of vectors or to multiply 
matrices or multiply a vector by a matrix.

In [13]:
a=np.array([9,10])
b=np.array([11, 12])
print(a.dot(b))
#or
print(np.dot(a,b))

219
219


In [17]:
# Matrix / vector product; both produce the rank 1 array [29 67]
#print(x.cross(a))
#or
print(np.cross(x,a))

[[-70  63 -15]
 [-10   9  29]]


NumPy provides many useful functions for performing computations on arrays. One 
of the most useful is sum.

In [22]:
x=np.array([[1,2],[3,4]])
# Compute sum of all elements
print(np.sum(x))
# Compute sum of each column
print(np.sum(x, axis=0))
# Compute sum of each row
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


Transpose is one of the common operations often performed on matrix, which can 
be achieved using the T attribute of an array object. 

In [26]:
x=np.array([[2,4],[6,8]])
y=np.array([1,2,3,4])
#normal
print(x)
print(y)
#transpose 
print(x.T)
print(y.T)

[[2 4]
 [6 8]]
[1 2 3 4]
[[2 6]
 [4 8]]
[1 2 3 4]
