<a href="https://colab.research.google.com/github/Jakiaa/Python-Basic/blob/main/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Create a rank 1 array
a=np.array([0,1,2])
print(a)

[0 1 2]


In [ ]:
# Create a rank 2 array
b=np.array([[0,1,2],[4,5,6]])
print(b)

[[0 1 2]
 [4 5 6]]


In [ ]:
# Create a 3x3 array of all zeros
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create a 2x3 array of all ones
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a 3x3 constant array
b=np.full((3,3),7)
print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Create a 3x3 array filled with random values
b=np.random.random((3,3))
print(b)

[[0.72912516 0.07284922 0.47925603]
 [0.02886924 0.02429309 0.92494733]
 [0.09320652 0.22989021 0.40218351]]


In [ ]:
# Create a 3x3 identity matrix
b=np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# arange() will create arrays with regularly 
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# note mix of tuple and lists
b=np.array([[1,2,3],(1+1j,4,2)])
print(b)

[[1.+0.j 2.+0.j 3.+0.j]
 [1.+1.j 4.+0.j 2.+0.j]]


In [ ]:
# create an array of range with float data type
b=np.arange(1,8,dtype=np.float)
print(b)

[1. 2. 3. 4. 5. 6. 7.]


<ipython-input-17-d18a75a3cdbc>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.arange(1,8,dtype=np.float)
